# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JUennbxE6-OCHXbHgUdPXvxHP4ErrHMl
"""

import os
import zipfile
import joblib
import numpy as np
import pandas as pd
import lightgbm as lgb
from catboost import CatBoostClassifier
from sklearn.isotonic import IsotonicRegression
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import brier_score_loss

# 1. 경로 설정
PROJECT_PATH = '/content/drive/MyDrive/Colab Notebooks/공모전/lg_aimers_9'
DATA_DIR = os.path.join(PROJECT_PATH, 'data')
MODEL_DIR = os.path.join(PROJECT_PATH, 'model')
os.makedirs(MODEL_DIR, exist_ok=True)

print("1. Trackman 세부 데이터 정교 집계 중...")
tm_df = pd.read_csv(os.path.join(DATA_DIR, 'trackman_history.csv'))

# 투수별 구속, 회전수, 무브먼트의 평균 및 변동성(STD)
tm_pitcher = tm_df.groupby('pitcher_trackman_id').agg(
    tm_p_speed_mean=('rel_speed', 'mean'),
    tm_p_speed_std=('rel_speed', 'std'),
    tm_p_spin_mean=('spin_rate', 'mean'),
    tm_p_vbreak_mean=('induced_vert_break', 'mean'),
    tm_p_hbreak_mean=('horz_break', 'mean')
).reset_index().rename(columns={'pitcher_trackman_id': 'pitcher_id'})

# 타자별 상대한 구속/회전수 평균
tm_batter = tm_df.groupby('batter_trackman_id').agg(
    tm_b_speed_mean=('rel_speed', 'mean'),
    tm_b_spin_mean=('spin_rate', 'mean'),
    tm_b_vbreak_mean=('induced_vert_break', 'mean')
).reset_index().rename(columns={'batter_trackman_id': 'batter_id'})

tm_pitcher.to_csv(os.path.join(MODEL_DIR, 'tm_pitcher.csv'), index=False)
tm_batter.to_csv(os.path.join(MODEL_DIR, 'tm_batter.csv'), index=False)

# 2. 정교한 피처 엔지니어링 함수
def advanced_feature_engineering(df, tm_p, tm_b):
    df = df.copy()

    # 조인
    df = df.merge(tm_p, on='pitcher_id', how='left')
    df = df.merge(tm_b, on='batter_id', how='left')

    # Cold-Start Fallback (Trackman 결측치를 전체 평균으로 대치)
    for col in tm_p.columns:
        if col != 'pitcher_id':
            df[col] = df[col].fillna(df[col].mean())
    for col in tm_b.columns:
        if col != 'batter_id':
            df[col] = df[col].fillna(df[col].mean())

    # [상성 및 상대 지표]
    df['speed_diff'] = df['tm_p_speed_mean'] - df['tm_b_speed_mean']
    df['spin_diff'] = df['tm_p_spin_mean'] - df['tm_b_spin_mean']
    df['vbreak_diff'] = df['tm_p_vbreak_mean'] - df['tm_b_vbreak_mean']

    # [야구 도메인 & 카운트 정교화]
    df['count_state'] = df['balls_before'].astype(str) + "B_" + df['strikes_before'].astype(str) + "S"
    df['is_hitter_advantage'] = (df['balls_before'] > df['strikes_before']).astype(int)
    df['is_two_strikes'] = (df['strikes_before'] == 2).astype(int)
    df['is_full_count'] = ((df['balls_before'] == 3) & (df['strikes_before'] == 2)).astype(int)
    df['is_platoon_advantage'] = (df['pitcher_hand'] == df['batter_hand']).astype(int)

    # [최근 경기 흐름 & 폼 피처]
    df['recent_form_diff'] = df['asof_pitcher_prev1_game_success_rate'].fillna(0) - df['asof_pitcher_success_rate'].fillna(0)
    df['recent_3g_diff'] = df['asof_pitcher_prev3_game_success_rate'].fillna(0) - df['asof_pitcher_success_rate'].fillna(0)

    # [Bayesian Smoothing]
    global_mean_success = 0.55
    m = 20.0
    n = df['asof_pitcher_n'].fillna(0)
    rate = df['asof_pitcher_success_rate'].fillna(global_mean_success)
    df['asof_pitcher_success_smoothed'] = (n * rate + m * global_mean_success) / (n + m)

    # [구종 조합 비율]
    df['fastball_ratio'] = df['asof_pitcher_fastball_rate'].fillna(0)
    df['breaking_ratio'] = df['asof_pitcher_breaking_rate'].fillna(0)
    df['offspeed_ratio'] = df['asof_pitcher_offspeed_rate'].fillna(0)

    # 범주형 변수 처리
    cat_cols = ['top_bottom', 'game_type', 'base_state', 'count_state',
                'pitcher_hand', 'batter_hand', 'pitcher_team_id', 'batter_team_id']
    for c in cat_cols:
        if c in df.columns:
            df[c] = df[c].astype(str)

    return df

print("2. Train 데이터 정교 전처리 적용 중...")
train_raw = pd.read_csv(os.path.join(DATA_DIR, 'train.csv'))
train_df = advanced_feature_engineering(train_raw, tm_pitcher, tm_batter)

drop_cols = ['row_id', 'control_success']
feature_cols = [c for c in train_df.columns if c not in drop_cols]
cat_cols = ['top_bottom', 'game_type', 'base_state', 'count_state',
            'pitcher_hand', 'batter_hand', 'pitcher_team_id', 'batter_team_id']

X = train_df[feature_cols]
y = train_df['control_success']

# LightGBM용 범주형 타입
X_lgb = X.copy()
for c in cat_cols:
    X_lgb[c] = X_lgb[c].astype('category')

# 3. K-Fold 앙상블 학습
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
oof_preds = np.zeros(len(train_df))

lgb_params = {
    'objective': 'binary',
    'metric': 'binary_logloss',
    'learning_rate': 0.03,
    'num_leaves': 127,
    'max_depth': -1,
    'min_child_samples': 40,
    'subsample': 0.8,
    'colsample_bytree': 0.8,
    'random_state': 42,
    'n_jobs': -1,
    'verbose': -1
}

print("3. LightGBM & CatBoost 고성능 앙상블 학습 시작...")
for fold, (train_idx, val_idx) in enumerate(skf.split(X, y)):
    print(f"--- Fold {fold+1} 진행 중 ---")
    X_tr_lgb, y_tr = X_lgb.iloc[train_idx], y.iloc[train_idx]
    X_val_lgb, y_val = X_lgb.iloc[val_idx], y.iloc[val_idx]

    # LightGBM
    model_lgb = lgb.LGBMClassifier(**lgb_params, n_estimators=1200)
    model_lgb.fit(X_tr_lgb, y_tr, eval_set=[(X_val_lgb, y_val)], callbacks=[lgb.early_stopping(50, verbose=False)])
    p_lgb = model_lgb.predict_proba(X_val_lgb)[:, 1]

    # CatBoost
    X_tr_cb, X_val_cb = X.iloc[train_idx], X.iloc[val_idx]
    model_cb = CatBoostClassifier(iterations=1200, learning_rate=0.03, depth=6, cat_features=cat_cols, random_seed=42, verbose=0)
    model_cb.fit(X_tr_cb, y_tr, eval_set=(X_val_cb, y_val), early_stopping_rounds=50)
    p_cb = model_cb.predict_proba(X_val_cb)[:, 1]

    oof_preds[val_idx] = 0.5 * p_lgb + 0.5 * p_cb

# 4. Calibration
calibrator = IsotonicRegression(out_of_bounds='clip')
calibrated_oof = calibrator.fit_transform(oof_preds, y)

brier = brier_score_loss(y, calibrated_oof)
r = y.mean()
bss_score = max(0, 100000 * (1 - brier / (r * (1 - r))))
print(f"\n[검증 결과] 고도화 OOF Brier Skill Score: {bss_score:.2f}")

# 5. 전체 데이터 재학습
final_lgb = lgb.LGBMClassifier(**lgb_params, n_estimators=800)
final_lgb.fit(X_lgb, y)

final_cb = CatBoostClassifier(iterations=800, learning_rate=0.03, depth=6, cat_features=cat_cols, random_seed=42, verbose=0)
final_cb.fit(X, y)

joblib.dump(final_lgb, os.path.join(MODEL_DIR, 'lgbm_model.pkl'))
joblib.dump(final_cb, os.path.join(MODEL_DIR, 'catboost_model.pkl'))
joblib.dump(calibrator, os.path.join(MODEL_DIR, 'calibrator.pkl'))
joblib.dump(feature_cols, os.path.join(MODEL_DIR, 'feature_cols.pkl'))

# 6. script.py 자동 생성
script_content = '''import os
import sys
import joblib
import pandas as pd
import numpy as np

def advanced_feature_engineering(df, tm_p, tm_b):
    df = df.copy()
    df = df.merge(tm_p, on='pitcher_id', how='left')
    df = df.merge(tm_b, on='batter_id', how='left')

    for col in tm_p.columns:
        if col != 'pitcher_id':
            df[col] = df[col].fillna(df[col].mean())
    for col in tm_b.columns:
        if col != 'batter_id':
            df[col] = df[col].fillna(df[col].mean())

    df['speed_diff'] = df['tm_p_speed_mean'] - df['tm_b_speed_mean']
    df['spin_diff'] = df['tm_p_spin_mean'] - df['tm_b_spin_mean']
    df['vbreak_diff'] = df['tm_p_vbreak_mean'] - df['tm_b_vbreak_mean']

    df['count_state'] = df['balls_before'].astype(str) + "B_" + df['strikes_before'].astype(str) + "S"
    df['is_hitter_advantage'] = (df['balls_before'] > df['strikes_before']).astype(int)
    df['is_two_strikes'] = (df['strikes_before'] == 2).astype(int)
    df['is_full_count'] = ((df['balls_before'] == 3) & (df['strikes_before'] == 2)).astype(int)
    df['is_platoon_advantage'] = (df['pitcher_hand'] == df['batter_hand']).astype(int)

    df['recent_form_diff'] = df['asof_pitcher_prev1_game_success_rate'].fillna(0) - df['asof_pitcher_success_rate'].fillna(0)
    df['recent_3g_diff'] = df['asof_pitcher_prev3_game_success_rate'].fillna(0) - df['asof_pitcher_success_rate'].fillna(0)

    global_mean_success = 0.55
    m = 20.0
    n = df['asof_pitcher_n'].fillna(0)
    rate = df['asof_pitcher_success_rate'].fillna(global_mean_success)
    df['asof_pitcher_success_smoothed'] = (n * rate + m * global_mean_success) / (n + m)

    df['fastball_ratio'] = df['asof_pitcher_fastball_rate'].fillna(0)
    df['breaking_ratio'] = df['asof_pitcher_breaking_rate'].fillna(0)
    df['offspeed_ratio'] = df['asof_pitcher_offspeed_rate'].fillna(0)

    cat_cols = ['top_bottom', 'game_type', 'base_state', 'count_state',
                'pitcher_hand', 'batter_hand', 'pitcher_team_id', 'batter_team_id']
    for c in cat_cols:
        if c in df.columns:
            df[c] = df[c].astype(str)

    return df

def main():
    DATA_DIR = "data"
    MODEL_DIR = "model"
    OUTPUT_DIR = "output"

    test_path = os.path.join(DATA_DIR, "test.csv")
    output_path = os.path.join(OUTPUT_DIR, "submission.csv")

    os.makedirs(OUTPUT_DIR, exist_ok=True)
    if not os.path.exists(test_path):
        sys.exit(1)

    test_df = pd.read_csv(test_path)
    tm_p = pd.read_csv(os.path.join(MODEL_DIR, "tm_pitcher.csv"))
    tm_b = pd.read_csv(os.path.join(MODEL_DIR, "tm_batter.csv"))

    lgb_model = joblib.load(os.path.join(MODEL_DIR, "lgbm_model.pkl"))
    cb_model = joblib.load(os.path.join(MODEL_DIR, "catboost_model.pkl"))
    calibrator = joblib.load(os.path.join(MODEL_DIR, "calibrator.pkl"))
    feature_cols = joblib.load(os.path.join(MODEL_DIR, "feature_cols.pkl"))

    X_test_raw = advanced_feature_engineering(test_df, tm_p, tm_b)
    X_test = X_test_raw[feature_cols]

    X_test_lgb = X_test.copy()
    cat_cols = ['top_bottom', 'game_type', 'base_state', 'count_state',
                'pitcher_hand', 'batter_hand', 'pitcher_team_id', 'batter_team_id']
    for c in cat_cols:
        X_test_lgb[c] = X_test_lgb[c].astype('category')

    p_lgb = lgb_model.predict_proba(X_test_lgb)[:, 1]
    p_cb = cb_model.predict_proba(X_test)[:, 1]

    raw_preds = 0.5 * p_lgb + 0.5 * p_cb
    calibrated_preds = calibrator.transform(raw_preds)

    submission = pd.DataFrame({
        'row_id': test_df['row_id'],
        'control_success': calibrated_preds
    })

    submission.to_csv(output_path, index=False)

if __name__ == "__main__":
    main()
'''

with open(os.path.join(PROJECT_PATH, 'script.py'), 'w', encoding='utf-8') as f:
    f.write(script_content)

# requirements.txt
with open(os.path.join(PROJECT_PATH, 'requirements.txt'), 'w', encoding='utf-8') as f:
    f.write('lightgbm>=4.0.0\ncatboost>=1.2.0\n')

# submit.zip
zip_path = os.path.join(PROJECT_PATH, 'submit.zip')
with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
    for root, _, files in os.walk(MODEL_DIR):
        for file in files:
            full_path = os.path.join(root, file)
            arcname = os.path.relpath(full_path, PROJECT_PATH)
            zipf.write(full_path, arcname)
    zipf.write(os.path.join(PROJECT_PATH, 'script.py'), 'script.py')
    zipf.write(os.path.join(PROJECT_PATH, 'requirements.txt'), 'requirements.txt')

print("\n고도화 submit.zip 생성 완료! 구글 드라이브에서 다운로드하여 제출해 보세요.")