# -*- coding: utf-8 -*-
"""feature_validation_CatBoost.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1otppxkcHkbY6JeNZxBEQN1Ub3tGrUBUg

# Feature Validation with CatBoost
##0. 설정
"""

!pip install -q catboost

import gc
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from catboost import CatBoostClassifier, Pool

warnings.filterwarnings("ignore")
pd.set_option("display.max_columns", 200)
pd.set_option("display.width", 220)
sns.set_theme(style="whitegrid")

# 한글 폰트 (설치 후 런타임 재시작 필요)
!apt-get -qq install fonts-nanum > /dev/null
import matplotlib.font_manager as fm
fm.fontManager.addfont("/usr/share/fonts/truetype/nanum/NanumGothic.ttf")
plt.rc("font", family="NanumGothic")
plt.rc("axes", unicode_minus=False)

BASE = Path("/content/drive/MyDrive/open")
CACHE_DIR = BASE / "cache"
ARTIFACT_DIR = BASE / "artifacts"; ARTIFACT_DIR.mkdir(parents=True, exist_ok=True)

ID, TARGET = "row_id", "control_success"
CAT_COLS = ["top_bottom", "game_type", "base_state"]

# GPU 사용 가능 여부 — 1.1M 행 학습이 수 분에서 수십 초로 단축됨
import torch
USE_GPU = torch.cuda.is_available()
print(f"GPU: {USE_GPU}")

"""## 1. 데이터 로드"""

!fusermount -uz /content/drive 2>/dev/null
!umount -l /content/drive 2>/dev/null
!rm -rf /content/drive
!mkdir -p /content/drive
!ls -la /content/drive

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_parquet(CACHE_DIR / "train_feat_all.parquet")
print(f"{df.shape}  ({df.memory_usage(deep=True).sum()/1024**2:,.0f} MB)")

# 원본 47개 / 신규 40개 구분
BASE_FEATS = [c for c in df.columns
              if not c.startswith(("tm_", "count_", "is_", "form_", "recent_",
                                   "pressure_", "hand_", "skill_", "f_share",
                                   "career_", "residual", "speed_diff",
                                   "spin_diff", "vbreak_diff", "pitcher_control",
                                   "asof_pitcher_success_smoothed"))
              and c not in [ID, TARGET]]
NEW_FEATS = [c for c in df.columns if c not in BASE_FEATS + [ID, TARGET]]
ALL_FEATS = BASE_FEATS + NEW_FEATS

print(f"기존 {len(BASE_FEATS)}개 / 신규 {len(NEW_FEATS)}개 / 전체 {len(ALL_FEATS)}개")

"""### 1) 상수 컬럼 점검"""

const = [c for c in ALL_FEATS if df[c].nunique(dropna=True) <= 1]
print("상수 컬럼:", const if const else "없음")

print("\n결측률 상위 10 (%)")
print((df[NEW_FEATS].isna().mean() * 100).round(2).nlargest(10))

"""---
## 2. 공통 검증 프레임
"""

# 학습 구간 C안 — 2019~2022 퓨처스는 라벨 정의가 달라 제외
clean = df[~((df["game_type"] == "F") & (df["season"] <= 2022))].reset_index(drop=True)
print(f"오염 제거: {len(df):,} -> {len(clean):,}")

tr_mask = (clean["season"] <= 2023).to_numpy()
va_mask = (clean["season"] == 2024).to_numpy()
y = clean[TARGET].to_numpy()
print(f"train {tr_mask.sum():,} / valid {va_mask.sum():,}")


def decompose(y_true, p, n_bins=20):
    """Brier = REL - RES + UNC

    REL 낮을수록 좋음 (예측 확률이 실제 빈도와 일치)
    RES 높을수록 좋음 (투구별 분별력)

    피처 비교는 RES 로 한다. BSS 는 확률 보정 여부에 따라
    100점 단위로 흔들려 단독 비교 지표로 부적합하다.
    """
    y_true = np.asarray(y_true, float)
    p = np.asarray(p, float)
    r, n = y_true.mean(), len(y_true)
    edges = np.quantile(p, np.linspace(0, 1, n_bins + 1))
    edges[0] -= 1e-9; edges[-1] += 1e-9
    idx = np.digitize(p, edges[1:-1])
    rel = res = 0.0
    for k in np.unique(idx):
        m = idx == k
        w = m.sum() / n
        rel += w * (p[m].mean() - y_true[m].mean()) ** 2
        res += w * (y_true[m].mean() - r) ** 2
    return {"BSS": 100000 * (res - rel) / (r * (1 - r)),
            "REL": rel, "RES": res, "mean_pred-r": p.mean() - r}

"""### 1) CatBoost 입력 준비"""

def make_pool(idx, feats):
    X = clean.loc[idx, feats].copy()
    cats = [c for c in CAT_COLS if c in feats]
    for c in cats:
        X[c] = X[c].astype(str).fillna("NA")
    return Pool(X, clean.loc[idx, TARGET], cat_features=cats)


def run_cat(tag, feats, seed=42, iters=1000, verbose=False):
    """학습 → 2024 예측 → REL/RES 분해"""
    model = CatBoostClassifier(
        iterations=iters,
        learning_rate=0.05,
        depth=6,
        l2_leaf_reg=6.0,
        loss_function="Logloss",
        eval_metric="Logloss",
        random_seed=seed,
        task_type="GPU" if USE_GPU else "CPU",
        verbose=200 if verbose else 0,
        allow_writing_files=False,
    )
    tr_idx = np.flatnonzero(tr_mask)
    va_idx = np.flatnonzero(va_mask)
    model.fit(make_pool(tr_idx, feats))
    p = model.predict_proba(make_pool(va_idx, feats))[:, 1]
    d = decompose(y[va_idx], p)
    print(f"[{tag}] 피처 {len(feats)}개  "
          f"BSS {d['BSS']:8.2f}  REL {d['REL']:.6f}  RES {d['RES']:.6f}  "
          f"mean_pred-r {d['mean_pred-r']:+.4f}")
    return model, p, d

"""---
## 3. 베이스라인 vs 통합 피처셋
### 1) 신규 피처 40개의 기여도 확인
"""

results = {}

model_base, p_base, d_base = run_cat("기존 47개", BASE_FEATS)
results["기존 47개"] = d_base

model_all, p_all, d_all = run_cat("통합 87개", ALL_FEATS)
results["통합 87개"] = d_all

print(f"\nΔRES = {d_all['RES'] - d_base['RES']:+.6f} "
      f"({(d_all['RES']/d_base['RES'] - 1)*100:+.1f}%)")

"""### 2) 노이즈 크기 측정"""

noise = []
for s in [42, 7, 2024]:
    _, _, d = run_cat(f"기존 47개 seed={s}", BASE_FEATS, seed=s)
    noise.append(d["RES"])

NOISE = max(noise) - min(noise)
print(f"\n난수 변동폭 {NOISE:.6f}")
print(f"→ ΔRES 가 이 값보다 작으면 채택 근거 불충분")

"""### 3) 통합 피처셋"""

all_res = [0.001853]          # 이미 나온 값
for s in [7, 2024]:
    _, _, d = run_cat(f"통합 88 s={s}", ALL_FEATS, seed=s)
    all_res.append(d["RES"])

base_res = [0.001727, 0.001733, 0.001659, 0.001690,
            0.001738, 0.001650, 0.001634]

mb, sb = np.mean(base_res), np.std(base_res, ddof=1)
ma, sa = np.mean(all_res), np.std(all_res, ddof=1)
se = np.sqrt(sb**2/len(base_res) + sa**2/len(all_res))

print(f"\n기준선 {mb:.6f} ± {sb:.6f}  (n={len(base_res)})")
print(f"통합   {ma:.6f} ± {sa:.6f}  (n={len(all_res)})")
print(f"Δ = {ma-mb:+.6f} ± {se:.6f}  ({(ma-mb)/se:.1f}σ)")
print(f"상대 개선 {(ma-mb)/mb*100:+.1f}%")

"""---
## 4. 피처 중요도

| 방식 | 계산 기준 | 특징 |
| --- | --- | --- |
| `LossFunctionChange` | 학습 데이터 | 빠름. 약한 신호에서 과대평가 경향 |
| `permutation_importance` | 검증 데이터 | 느림. **실제 예측 기여를 직접 측정** |

### 4-1. CatBoost LossFunctionChange
"""

va_idx = np.flatnonzero(va_mask)
pool_va = make_pool(va_idx, ALL_FEATS)

imp_cat = pd.Series(
    model_all.get_feature_importance(pool_va, type="LossFunctionChange"),
    index=ALL_FEATS).sort_values(ascending=False)

print("=== 상위 20 ===")
print(imp_cat.head(20).round(6))
print("\n=== 하위 20 ===")
print(imp_cat.tail(20).round(6))

"""### 4-2. Permutation Importance"""

def perm_importance(model, X, y, feats, cats, n_repeats=5, seed=42):
    """예측만 반복하는 permutation importance.
    학습 변동이 개입하지 않아 노이즈 0.000043 문제에서 자유롭다."""
    rng = np.random.default_rng(seed)

    def score(Xd):
        p = model.predict_proba(Xd)[:, 1]
        return -((p - y) ** 2).mean()      # neg Brier

    base = score(X)
    print(f"기준 neg-Brier {base:.6f}")

    rows = []
    for i, f in enumerate(feats, 1):
        drops = []
        col = X[f].to_numpy(copy=True)
        for _ in range(n_repeats):
            Xp = X.copy()
            Xp[f] = rng.permutation(col)
            drops.append(base - score(Xp))
        rows.append({"피처": f, "중요도": np.mean(drops), "표준편차": np.std(drops)})
        if i % 10 == 0:
            print(f"  {i}/{len(feats)}")

    return (pd.DataFrame(rows).sort_values("중요도", ascending=False)
            .reset_index(drop=True))


rng = np.random.default_rng(42)
sub = rng.choice(np.flatnonzero(va_mask), size=min(60_000, va_mask.sum()), replace=False)

Xs = clean.loc[sub, ALL_FEATS].copy()
for c in CAT_COLS:
    Xs[c] = Xs[c].astype(str)
ys = clean.loc[sub, TARGET].to_numpy().astype(float)

imp_perm = perm_importance(model_all, Xs, ys, ALL_FEATS, CAT_COLS)

print("\n=== 상위 25 ===")
print(imp_perm.head(25).round(8).to_string(index=False))

"""### 4-3. 신규 피처 따로"""

new_imp = imp_perm[imp_perm["피처"].isin(NEW_FEATS)].copy()
new_imp["σ"] = new_imp["중요도"] / new_imp["표준편차"].replace(0, np.nan)
new_imp["유의"] = new_imp["σ"] >= 2

print(f"신규 {len(NEW_FEATS)}개 중 유의 {new_imp['유의'].sum()}개\n")
print(new_imp.round(8).to_string(index=False))

fig, ax = plt.subplots(figsize=(8, 11))
s = new_imp.sort_values("중요도")
ax.barh(s["피처"], s["중요도"], xerr=s["표준편차"],
        color=["#2c3e50" if v else "#bdc3c7" for v in s["유의"]])
ax.axvline(0, color="r", lw=1, ls="--")
ax.set_xlabel("permutation importance (neg Brier)")
ax.set_title("신규 41개 — 진한 색이 유의")
plt.tight_layout(); plt.show()

"""### 4-4. 그룹 제거 실험"""

SIG = ["asof_pitcher_success_smoothed", "f_share", "tm_offspeed_rate",
       "hand_match", "tm_p_speed_mean", "tm_horz_break_mean",
       "tm_p_hbreak_mean", "tm_b_vbreak_mean", "tm_p_spin_mean", "count_depth"]
HARM = ["tm_breaking_rate", "recent_trend_middle"]

SETS = {
    "A. 유의 10개만":   BASE_FEATS + SIG,
    "B. 전체 41개":     ALL_FEATS,
    "C. 유해 2개 제외": [c for c in ALL_FEATS if c not in HARM],
}

out = {}
for tag, feats in SETS.items():
    rs = []
    for s in [42, 7, 2024]:
        _, _, d = run_cat(f"{tag} s={s}", feats, seed=s)
        rs.append(d["RES"])
    out[tag] = (np.mean(rs), np.std(rs, ddof=1), len(feats))
    print(f"  → {tag}: {np.mean(rs):.6f} ± {np.std(rs, ddof=1):.6f}\n")

base_m = 0.001690
for tag, (m, sd, n) in out.items():
    print(f"{tag:16s} 피처{n:3d}  RES {m:.6f} ± {sd:.6f}  Δ기준선 {m-base_m:+.6f}")

"""---
## 5. 중복 피처 탐지
"""

num_feats = [c for c in ALL_FEATS if c not in CAT_COLS]
samp = clean[num_feats].sample(min(200_000, len(clean)), random_state=42).astype(float)
corr = samp.corr()

pairs = []
for i, a in enumerate(num_feats):
    for b in num_feats[i+1:]:
        v = corr.loc[a, b]
        if abs(v) >= 0.90:
            ra = imp_perm.set_index("피처").loc[a, "중요도"]
            rb = imp_perm.set_index("피처").loc[b, "중요도"]
            keep, drop = (a, b) if ra >= rb else (b, a)
            pairs.append({"A": a, "B": b, "상관": round(v, 4),
                          "유지": keep, "제거후보": drop})

dup = pd.DataFrame(pairs).sort_values("상관", key=abs, ascending=False)
print(f"|r| >= 0.90 쌍 {len(dup)}건")
print(dup.to_string(index=False))

del samp; gc.collect()

"""---
## 6. 시즌 교락 검증
"""

from scipy.stats import spearmanr

rows = []
for c in NEW_FEATS:
    if c in CAT_COLS:
        continue
    r_season = clean[[c, "season"]].astype(float).corr().iloc[0, 1]

    rhos = []
    for s in [2021, 2022, 2023, 2024]:
        d = clean[(clean["season"] == s) & clean[c].notna()]
        if len(d) < 20_000 or d[c].nunique() < 5:
            rhos.append(np.nan); continue
        q = pd.qcut(d[c], 5, duplicates="drop", labels=False)
        g = d.groupby(q, observed=True)[TARGET].mean()
        rhos.append(round(spearmanr(g.index, g.values)[0], 2))

    vals = [v for v in rhos if not np.isnan(v) and v != 0]
    consistent = (len(set(np.sign(vals))) == 1
                  and min(map(abs, vals)) >= 0.6) if len(vals) >= 3 else False

    rows.append({"피처": c, "season상관": round(r_season, 3),
                 "2021": rhos[0], "2022": rhos[1],
                 "2023": rhos[2], "2024": rhos[3],
                 "부호일치": consistent})

season_chk = pd.DataFrame(rows)
print(season_chk.to_string(index=False))

print(f"\n⚠️ season 상관 0.3 이상: "
      f"{season_chk[season_chk['season상관'].abs() >= 0.3]['피처'].tolist()}")
print(f"✅ 시즌 부호 일치: {season_chk[season_chk['부호일치']]['피처'].tolist()}")

"""---
## 7. 잔차 분석
"""

va_df = clean.loc[va_idx].copy()
va_df["pred"] = p_all
va_df["resid"] = va_df[TARGET] - va_df["pred"]

"""### 7-1. 캘리브레이션 곡선"""

q = pd.qcut(va_df["pred"], 20, duplicates="drop")
cal = va_df.groupby(q, observed=True).agg(
    예측=("pred", "mean"), 실제=(TARGET, "mean"), n=("pred", "size"))

fig, axes = plt.subplots(1, 2, figsize=(12, 4.5))
axes[0].plot([0.35, 0.65], [0.35, 0.65], "r--", lw=1, label="완벽 보정")
axes[0].plot(cal["예측"], cal["실제"], "o-", color="#2c3e50")
axes[0].set_xlabel("예측 확률"); axes[0].set_ylabel("실제 성공률")
axes[0].set_title("캘리브레이션 곡선"); axes[0].legend()

axes[1].hist(va_df["pred"], bins=50, color="#2c3e50")
axes[1].axvline(va_df[TARGET].mean(), color="r", ls="--", label="실제 기저율")
axes[1].set_xlabel("예측 확률"); axes[1].set_title("예측 분포"); axes[1].legend()
plt.tight_layout(); plt.show()

print(cal.round(4).to_string())
print(f"\n예측 범위 {va_df['pred'].min():.4f} ~ {va_df['pred'].max():.4f}")
print(f"예측 표준편차 {va_df['pred'].std():.4f}  ← 클수록 분별력 큼")

"""### 7-2. 세그먼트 별 편차"""

def resid_by(col, bins=None, label=None):
    d = va_df.copy()
    key = col
    if bins is not None:
        d["_bin"] = pd.cut(d[col], bins)
        key = "_bin"
    elif d[col].nunique() > 12:
        d["_bin"] = pd.qcut(d[col], 5, duplicates="drop")
        key = "_bin"
    g = d.groupby(key, observed=True).agg(
        n=("resid", "size"),
        평균잔차=("resid", "mean"),
        실제=(TARGET, "mean"),
        예측=("pred", "mean"),
        brier=("resid", lambda s: (s ** 2).mean()))
    g["비중"] = (g["n"] / len(d)).round(4)
    print(f"\n=== {label or col} ===")
    print(g.round(4).to_string())
    return g


for c in ["season", "game_type", "count_pressure", "count_depth",
          "inning", "is_cold_start", "pressure_score", "hand_match"]:
    if c in va_df.columns:
        resid_by(c)

resid_by("asof_pitcher_n", bins=[-1, 100, 500, 1500, 4000, 20000],
         label="투수 누적 투구수")
if "f_share" in va_df.columns:
    resid_by("f_share", bins=[-0.01, 0.001, 0.05, 0.2, 1.01],
             label="퓨처스 노출 비율")

"""### 7-3. 잔차에 남은 구조"""

resid_corr = (va_df[num_feats].astype(float)
              .corrwith(va_df["resid"]).abs()
              .sort_values(ascending=False).head(15))
print("=== 잔차와 상관 높은 피처 상위 15 ===")
print(resid_corr.round(5))
print("\n0.02 이상이면 아직 활용되지 않은 신호가 남아 있을 가능성")

"""### 7-4. 투수별 잔차"""

pit = (va_df.groupby("pitcher_id", observed=True)
       .agg(n=("resid", "size"), 평균잔차=("resid", "mean"),
            실제=(TARGET, "mean"), 예측=("pred", "mean")))
pit = pit[pit["n"] >= 300]

print(f"대상 투수 {len(pit)}명")
print(f"평균 잔차 표준편차 {pit['평균잔차'].std():.4f}")
print("\n과소예측 상위 5"); print(pit.nlargest(5, "평균잔차").round(4).to_string())
print("\n과대예측 상위 5"); print(pit.nsmallest(5, "평균잔차").round(4).to_string())

fig, ax = plt.subplots(figsize=(7, 4))
ax.hist(pit["평균잔차"], bins=40, color="#2c3e50")
ax.axvline(0, color="r", ls="--")
ax.set_xlabel("투수별 평균 잔차"); ax.set_ylabel("투수 수")
ax.set_title("투수별 잔차 분포")
plt.tight_layout(); plt.show()

"""---
## 8. 최종 피처 선정

[결론] 41개 → 31개 (10개 제거)

제거 기준: 개별 중요도가 아니라 구조적 결함
  - test 범위 밖 값: `career_span`
  - 수치 불안정: `pitcher_control_ratio`
  - 구성상 중복(r>0.9): `speed/spin/vbreak_diff`, `form_dev_1`
  - 다중공선: `tm_breaking_rate`
  - 정의 오류: `tm_p_speed_std` (구종 혼합)
  - 유의한 음의 기여: `recent_trend_middle`

유지한 근거:
  `count_pressure`·`pressure_score`·`skill_gap` 등은 permutation 0이지만
  시즌별 5분위 순위상관이 4시즌 모두 ±1.0 → 원본과 중복일 뿐 신호는 확실
  유의 10개만 남긴 세트는 전체 대비 RES 하락(p≈0.07, 확정은 아니나 방향은 일관)
"""

DROP = ["career_span", "pitcher_control_ratio",
        "speed_diff", "spin_diff", "vbreak_diff",
        "tm_breaking_rate", "recent_trend_middle",
        "tm_p_speed_std", "form_dev_1"]
FINAL_FEATS = [c for c in ALL_FEATS if c not in DROP]   # 79개

rs = [run_cat(f"D. 79개 s={s}", FINAL_FEATS, seed=s)[2]["RES"] for s in [42,7,2024]]
print(f"D (79): {np.mean(rs):.6f} ± {np.std(rs, ddof=1):.6f}")
print(f"B (88): 0.001880 ± 0.000014")

